site_name: Current Affairs
nav:
  - Home: index.md
  - January:
             - January/2023-01-02.md
             - January/2023-01-03.md
             - January/2023-01-04.md
             - January/2023-01-05.md
             - January/2023-01-06.md
             - January/2023-01-07.md
             - January/2023-01-09.md
             - January/2023-01-10.md
             - January/2023-01-11.md
             - January/2023-01-12.md
             - January/2023-01-13.md
             - January/2023-01-14.md
             - January/2023-01-16.md
             - January/2023-01-17.md
             - January/2023-01-18.md
             - January/2023-01-19.md
             - January/2023-01-20.md
             - January/2023-01-21.md
             - January/2023-01-23.md
             - January/2023-01-24.md
             - January/2023-01-25.md
             - January/2023-01-26.md
             - January/2023-01-27.md
             - January/2023-01-28.md
             - January/2023-01-30.md
             - January/2023-01-31.md
  - February:
             - February/2023-02-01.md
             - February/2023-02-02.md
             - February/2023-02-03.md
             - February/2023-02-04.md
             - February/2023-02-06.md
             - February/2023-02-07.md
             - February/2023-02-08.md
             - February/2023-02-09.md
             - February/2023-02-10.md
             - February/2023-02-11.md
             - February/2023-02-13.md
             - February/2023-02-14.md
             - February/2023-02-15.md
             - February/2023-02-16.md
             - February/2023-02-17.md
             - February/2023-02-18.md
             - February/2023-02-20.md
             - February/2023-02-21.md
             - February/2023-02-22.md
             - February/2023-02-23.md
             - February/2023-02-24.md
             - February/2023-02-25.md
             - February/2023-02-27.md
             - February/2023-02-28.md
  - March:
             - March/2023-03-01.md
             - March/2023-03-02.md
             - March/2023-03-03.md
             - March/2023-03-04.md
             - March/2023-03-06.md
             - March/2023-03-07.md
             - March/2023-03-08.md
             - March/2023-03-09.md
             - March/2023-03-10.md
             - March/2023-03-11.md
             - March/2023-03-13.md
             - March/2023-03-14.md
             - March/2023-03-15.md
             - March/2023-03-16.md
             - March/2023-03-17.md
             - March/2023-03-18.md
             - March/2023-03-20.md
             - March/2023-03-21.md
             - March/2023-03-22.md
             - March/2023-03-23.md
             - March/2023-03-24.md
             - March/2023-03-25.md
             - March/2023-03-27.md
             - March/2023-03-28.md
             - March/2023-03-29.md
             - March/2023-03-30.md
             - March/2023-03-31.md
  - April:
             - April/2023-04-01.md
             - April/2023-04-03.md
             - April/2023-04-04.md
             - April/2023-04-05.md
             - April/2023-04-06.md
             - April/2023-04-07.md
             - April/2023-04-08.md
             - April/2023-04-10.md
             - April/2023-04-11.md
             - April/2023-04-12.md
             - April/2023-04-13.md
             - April/2023-04-14.md
             - April/2023-04-15.md
             - April/2023-04-17.md
             - April/2023-04-18.md
             - April/2023-04-19.md
             - April/2023-04-20.md
             - April/2023-04-21.md
             - April/2023-04-22.md
             - April/2023-04-24.md
             - April/2023-04-25.md
             - April/2023-04-26.md
             - April/2023-04-27.md
             - April/2023-04-28.md
             - April/2023-04-29.md
  - May:
             - May/2023-05-01.md
             - May/2023-05-02.md
             - May/2023-05-03.md
             - May/2023-05-04.md
             - May/2023-05-05.md
             - May/2023-05-06.md
             - May/2023-05-08.md
             - May/2023-05-09.md
             - May/2023-05-10.md
             - May/2023-05-11.md
             - May/2023-05-12.md
             - May/2023-05-13.md
             - May/2023-05-15.md
             - May/2023-05-16.md
             - May/2023-05-17.md
             - May/2023-05-18.md
             - May/2023-05-19.md
             - May/2023-05-20.md
             - May/2023-05-22.md
             - May/2023-05-23.md
             - May/2023-05-24.md
             - May/2023-05-25.md
             - May/2023-05-26.md
             - May/2023-05-27.md
             - May/2023-05-29.md
             - May/2023-05-30.md
             - May/2023-05-31.md
  - June:
             - June/2023-06-01.md
             - June/2023-06-02.md
             - June/2023-06-03.md
             - June/2023-06-05.md
             - June/2023-06-06.md
             - June/2023-06-07.md
             - June/2023-06-08.md
             - June/2023-06-09.md
             - June/2023-06-10.md
             - June/2023-06-12.md
             - June/2023-06-13.md
             - June/2023-06-14.md
             - June/2023-06-15.md
             - June/2023-06-16.md
             - June/2023-06-17.md
             - June/2023-06-19.md
             - June/2023-06-21.md
             - June/2023-06-22.md
             - June/2023-06-23.md
             - June/2023-06-24.md
             - June/2023-06-26.md
             - June/2023-06-27.md
             - June/2023-06-28.md
             - June/2023-06-29.md
             - June/2023-06-30.md
  - July:
             - July/2023-07-01.md
             - July/2023-07-03.md
             - July/2023-07-04.md
             - July/2023-07-05.md
             - July/2023-07-06.md
             - July/2023-07-07.md
             - July/2023-07-08.md
             - July/2023-07-10.md
             - July/2023-07-11.md
             - July/2023-07-12.md
             - July/2023-07-13.md
             - July/2023-07-14.md
             - July/2023-07-15.md
             - July/2023-07-17.md
             - July/2023-07-18.md
             - July/2023-07-19.md
             - July/2023-07-20.md
             - July/2023-07-21.md
             - July/2023-07-22.md
             - July/2023-07-24.md
             - July/2023-07-25.md
             - July/2023-07-26.md
             - July/2023-07-27.md
             - July/2023-07-28.md
             - July/2023-07-29.md
             - July/2023-07-31.md
                          
theme:
  name: material    
  features:
    - navigation.instant
    - navigation.instant.prefetch 
  palette:
    primary: blue grey
